# Generated by Django 6.0.1 on 2026-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.IntegerField(verbose_name='发起人ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
                ('category', models.CharField(max_length=20, verbose_name='类别')),
                ('event_time', models.DateTimeField(verbose_name='活动时间')),
                ('location', models.CharField(max_length=100, verbose_name='地点')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(verbose_name='活动ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'db_table': 'activity_participants',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('avatar_url', models.CharField(max_length=255, null=True, verbose_name='头像链接')),
                ('gender', models.CharField(max_length=10, null=True, verbose_name='性别')),
                ('tags', models.CharField(max_length=255, null=True, verbose_name='标签')),
                ('intro', models.TextField(null=True, verbose_name='个人介绍')),
                ('credit_score', models.IntegerField(default=100, verbose_name='信用值')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(verbose_name='发起者ID')),
                ('receiver_id', models.IntegerField(verbose_name='被喜欢者ID')),
                ('action_type', models.CharField(max_length=10, verbose_name='类型(like/pass)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'db_table': 'user_likes',
            },
        ),
    ]
