# Generated by Django 6.0.1 on 2026-02-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='cover_url',
            field=models.CharField(max_length=500, null=True, verbose_name='封面图URL'),
        ),
        migrations.AddField(
            model_name='activity',
            name='current_people',
            field=models.IntegerField(default=0, verbose_name='当前人数'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True, verbose_name='活动详情'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_people',
            field=models.IntegerField(default=10, verbose_name='最大人数'),
        ),
        migrations.AddField(
            model_name='activity',
            name='mode',
            field=models.CharField(max_length=50, null=True, verbose_name='活动形式'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.CharField(max_length=255, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='status',
            field=models.CharField(default='success', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=100, verbose_name='活动地点/场馆'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, verbose_name='活动标题'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=50, verbose_name='运动类型'),
        ),
    ]
