# Generated by Django 6.0.1 on 2026-02-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_core', '0002_remove_activity_category_activity_cover_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a_id', models.IntegerField(verbose_name='用户A')),
                ('user_b_id', models.IntegerField(verbose_name='用户B')),
                ('achievement_score', models.IntegerField(default=0, verbose_name='伙伴成就值')),
                ('co_exercise_count', models.IntegerField(default=0, verbose_name='共同运动次数')),
                ('co_exercise_duration', models.IntegerField(default=0, verbose_name='共同运动时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='成为伙伴时间')),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_info',
            field=models.CharField(max_length=100, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='activity',
            name='venue_name',
            field=models.CharField(max_length=100, null=True, verbose_name='场馆名称'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='地理位置'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='personal_achievement',
            field=models.IntegerField(default=0, verbose_name='个人成就值'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='school',
            field=models.CharField(max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='short_desc',
            field=models.CharField(max_length=50, null=True, verbose_name='一句话描述'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tags_habit',
            field=models.TextField(null=True, verbose_name='习惯与偏好标签'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tags_level',
            field=models.CharField(max_length=50, null=True, verbose_name='段位标签'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tags_sport',
            field=models.TextField(null=True, verbose_name='运动类型标签'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tags_target',
            field=models.CharField(max_length=50, null=True, verbose_name='目标标签'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=100, verbose_name='详细地址/定位'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='avatar_url',
            field=models.CharField(max_length=500, null=True, verbose_name='头像/照片'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='intro',
            field=models.TextField(null=True, verbose_name='个人简介(长文本)'),
        ),
    ]
